proc cr_bd_SoC { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# bootrom_wrapper, ariane_peripherals_wrapper_verilog, cva6_wrapper_verilog, clint_wrapper_verilog, debug_module_wrapper_verilog, axi_fan_control, interrupt_synchronizer, axi_riscv_atomics_wrapper_verilog



  # CHANGE DESIGN NAME HERE
  set design_name SoC

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:axi_bram_ctrl:4.1\
  xilinx.com:ip:xlconstant:1.1\
  xilinx.com:ip:axi_uart16550:2.0\
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:axi_quad_spi:3.2\
  digilentinc.com:IP:PmodGPIO:1.0\
  xilinx.com:ip:axi_iic:2.1\
  xilinx.com:ip:util_vector_logic:2.0\
  xilinx.com:ip:xlconcat:2.1\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:ip:mig_7series:4.2\
  xilinx.com:ip:xadc_wiz:3.3\
  xilinx.com:ip:system_ila:1.1\
  xilinx.com:ip:axi_dma:7.1\
  xilinx.com:ip:axi_ethernet:7.2\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  bootrom_wrapper\
  ariane_peripherals_wrapper_verilog\
  cva6_wrapper_verilog\
  clint_wrapper_verilog\
  debug_module_wrapper_verilog\
  axi_fan_control\
  interrupt_synchronizer\
  axi_riscv_atomics_wrapper_verilog\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }


##################################################################
# MIG PRJ FILE TCL PROCs
##################################################################

proc write_mig_file_SoC_mig_7series_0_0 { str_mig_prj_filepath } {

   file mkdir [ file dirname "$str_mig_prj_filepath" ]
   set mig_prj_file [open $str_mig_prj_filepath  w+]

   puts $mig_prj_file {﻿<?xml version="1.0" encoding="UTF-8" standalone="no" ?>}
   puts $mig_prj_file {<Project NoOfControllers="1">}
   puts $mig_prj_file {  }
   puts $mig_prj_file {<!-- IMPORTANT: This is an internal file that has been generated by the MIG software. Any direct editing or changes made to this file may result in unpredictable behavior or data corruption. It is strongly advised that users do not edit the contents of this file. Re-run the MIG GUI with the required settings if any of the options provided below need to be altered. -->}
   puts $mig_prj_file {  <ModuleName>SoC_mig_7series_0_0</ModuleName>}
   puts $mig_prj_file {  <dci_inouts_inputs>1</dci_inouts_inputs>}
   puts $mig_prj_file {  <dci_inputs>1</dci_inputs>}
   puts $mig_prj_file {  <Debug_En>OFF</Debug_En>}
   puts $mig_prj_file {  <DataDepth_En>1024</DataDepth_En>}
   puts $mig_prj_file {  <LowPower_En>ON</LowPower_En>}
   puts $mig_prj_file {  <XADC_En>Disabled</XADC_En>}
   puts $mig_prj_file {  <TargetFPGA>xc7k325t-ffg900/-2</TargetFPGA>}
   puts $mig_prj_file {  <Version>4.2</Version>}
   puts $mig_prj_file {  <SystemClock>Differential</SystemClock>}
   puts $mig_prj_file {  <ReferenceClock>Use System Clock</ReferenceClock>}
   puts $mig_prj_file {  <SysResetPolarity>ACTIVE LOW</SysResetPolarity>}
   puts $mig_prj_file {  <BankSelectionFlag>FALSE</BankSelectionFlag>}
   puts $mig_prj_file {  <InternalVref>0</InternalVref>}
   puts $mig_prj_file {  <dci_hr_inouts_inputs>50 Ohms</dci_hr_inouts_inputs>}
   puts $mig_prj_file {  <dci_cascade>0</dci_cascade>}
   puts $mig_prj_file {  <Controller number="0">}
   puts $mig_prj_file {    <MemoryDevice>DDR3_SDRAM/Components/MT41J256m16XX-107</MemoryDevice>}
   puts $mig_prj_file {    <TimePeriod>1111</TimePeriod>}
   puts $mig_prj_file {    <VccAuxIO>2.0V</VccAuxIO>}
   puts $mig_prj_file {    <PHYRatio>4:1</PHYRatio>}
   puts $mig_prj_file {    <InputClkFreq>200.02</InputClkFreq>}
   puts $mig_prj_file {    <UIExtraClocks>1</UIExtraClocks>}
   puts $mig_prj_file {    <MMCM_VCO>900</MMCM_VCO>}
   puts $mig_prj_file {    <MMCMClkOut0> 2.250</MMCMClkOut0>}
   puts $mig_prj_file {    <MMCMClkOut1>1</MMCMClkOut1>}
   puts $mig_prj_file {    <MMCMClkOut2>1</MMCMClkOut2>}
   puts $mig_prj_file {    <MMCMClkOut3>1</MMCMClkOut3>}
   puts $mig_prj_file {    <MMCMClkOut4>1</MMCMClkOut4>}
   puts $mig_prj_file {    <DataWidth>32</DataWidth>}
   puts $mig_prj_file {    <DeepMemory>1</DeepMemory>}
   puts $mig_prj_file {    <DataMask>1</DataMask>}
   puts $mig_prj_file {    <ECC>Disabled</ECC>}
   puts $mig_prj_file {    <Ordering>Normal</Ordering>}
   puts $mig_prj_file {    <BankMachineCnt>4</BankMachineCnt>}
   puts $mig_prj_file {    <CustomPart>FALSE</CustomPart>}
   puts $mig_prj_file {    <NewPartName/>}
   puts $mig_prj_file {    <RowAddress>15</RowAddress>}
   puts $mig_prj_file {    <ColAddress>10</ColAddress>}
   puts $mig_prj_file {    <BankAddress>3</BankAddress>}
   puts $mig_prj_file {    <MemoryVoltage>1.5V</MemoryVoltage>}
   puts $mig_prj_file {    <C0_MEM_SIZE>1073741824</C0_MEM_SIZE>}
   puts $mig_prj_file {    <UserMemoryAddressMap>BANK_ROW_COLUMN</UserMemoryAddressMap>}
   puts $mig_prj_file {    <PinSelection>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AC12" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AB8" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[10]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AA8" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[11]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AB12" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[12]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AA12" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[13]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AH9" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[14]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AE8" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[1]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AD8" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[2]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AC10" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[3]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AD9" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[4]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AA13" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[5]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AA10" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[6]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AA11" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[7]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="Y10" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[8]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="Y11" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_addr[9]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AE9" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_ba[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AB10" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_ba[1]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AC11" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_ba[2]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AF11" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_cas_n"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15" PADName="AC9" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_ck_n[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15" PADName="AB9" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_ck_p[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AJ9" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_cke[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AH12" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_cs_n[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AD4" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dm[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AF3" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dm[1]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AH4" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dm[2]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AF8" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dm[3]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AD3" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AF1" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[10]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AE4" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[11]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AE3" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[12]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AE5" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[13]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AF5" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[14]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AF6" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[15]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AJ4" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[16]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AH6" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[17]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AH5" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[18]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AH2" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[19]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AC2" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[1]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AJ2" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[20]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AJ1" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[21]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AK1" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[22]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AJ3" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[23]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AF7" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[24]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AG7" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[25]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AJ6" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[26]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AK6" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[27]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AJ8" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[28]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AK8" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[29]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AC1" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[2]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AK5" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[30]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AK4" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[31]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AC5" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[3]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AC4" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[4]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AD6" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[5]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AE6" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[6]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AC7" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[7]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AF2" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[8]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15_T_DCI" PADName="AE1" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dq[9]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15_T_DCI" PADName="AD1" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dqs_n[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15_T_DCI" PADName="AG3" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dqs_n[1]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15_T_DCI" PADName="AH1" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dqs_n[2]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15_T_DCI" PADName="AJ7" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dqs_n[3]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15_T_DCI" PADName="AD2" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dqs_p[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15_T_DCI" PADName="AG4" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dqs_p[1]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15_T_DCI" PADName="AG2" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dqs_p[2]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="DIFF_SSTL15_T_DCI" PADName="AH7" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_dqs_p[3]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AK9" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_odt[0]"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AE11" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_ras_n"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="LVCMOS15" PADName="AG5" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_reset_n"/>}
   puts $mig_prj_file {      <Pin IN_TERM="" IOSTANDARD="SSTL15" PADName="AG13" SLEW="" VCCAUX_IO="NORMAL" name="ddr3_we_n"/>}
   puts $mig_prj_file {    </PinSelection>}
   puts $mig_prj_file {    <System_Clock>}
   puts $mig_prj_file {      <Pin Bank="33" PADName="AD12/AD11(CC_P/N)" name="sys_clk_p/n"/>}
   puts $mig_prj_file {    </System_Clock>}
   puts $mig_prj_file {    <System_Control>}
   puts $mig_prj_file {      <Pin Bank="Select Bank" PADName="No connect" name="sys_rst"/>}
   puts $mig_prj_file {      <Pin Bank="Select Bank" PADName="No connect" name="init_calib_complete"/>}
   puts $mig_prj_file {      <Pin Bank="Select Bank" PADName="No connect" name="tg_compare_error"/>}
   puts $mig_prj_file {    </System_Control>}
   puts $mig_prj_file {    <TimingParameters>}
   puts $mig_prj_file {      <Parameters tcke="5" tfaw="35" tras="34" trcd="13.91" trefi="7.8" trfc="260" trp="13.91" trrd="6" trtp="7.5" twtr="7.5"/>}
   puts $mig_prj_file {    </TimingParameters>}
   puts $mig_prj_file {    <mrBurstLength name="Burst Length">8 - Fixed</mrBurstLength>}
   puts $mig_prj_file {    <mrBurstType name="Read Burst Type and Length">Sequential</mrBurstType>}
   puts $mig_prj_file {    <mrCasLatency name="CAS Latency">13</mrCasLatency>}
   puts $mig_prj_file {    <mrMode name="Mode">Normal</mrMode>}
   puts $mig_prj_file {    <mrDllReset name="DLL Reset">No</mrDllReset>}
   puts $mig_prj_file {    <mrPdMode name="DLL control for precharge PD">Slow Exit</mrPdMode>}
   puts $mig_prj_file {    <emrDllEnable name="DLL Enable">Enable</emrDllEnable>}
   puts $mig_prj_file {    <emrOutputDriveStrength name="Output Driver Impedance Control">RZQ/7</emrOutputDriveStrength>}
   puts $mig_prj_file {    <emrMirrorSelection name="Address Mirroring">Disable</emrMirrorSelection>}
   puts $mig_prj_file {    <emrCSSelection name="Controller Chip Select Pin">Enable</emrCSSelection>}
   puts $mig_prj_file {    <emrRTT name="RTT (nominal) - On Die Termination (ODT)">RZQ/6</emrRTT>}
   puts $mig_prj_file {    <emrPosted name="Additive Latency (AL)">0</emrPosted>}
   puts $mig_prj_file {    <emrOCD name="Write Leveling Enable">Disabled</emrOCD>}
   puts $mig_prj_file {    <emrDQS name="TDQS enable">Enabled</emrDQS>}
   puts $mig_prj_file {    <emrRDQS name="Qoff">Output Buffer Enabled</emrRDQS>}
   puts $mig_prj_file {    <mr2PartialArraySelfRefresh name="Partial-Array Self Refresh">Full Array</mr2PartialArraySelfRefresh>}
   puts $mig_prj_file {    <mr2CasWriteLatency name="CAS write latency">9</mr2CasWriteLatency>}
   puts $mig_prj_file {    <mr2AutoSelfRefresh name="Auto Self Refresh">Enabled</mr2AutoSelfRefresh>}
   puts $mig_prj_file {    <mr2SelfRefreshTempRange name="High Temparature Self Refresh Rate">Normal</mr2SelfRefreshTempRange>}
   puts $mig_prj_file {    <mr2RTTWR name="RTT_WR - Dynamic On Die Termination (ODT)">Dynamic ODT off</mr2RTTWR>}
   puts $mig_prj_file {    <PortInterface>AXI</PortInterface>}
   puts $mig_prj_file {    <AXIParameters>}
   puts $mig_prj_file {      <C0_C_RD_WR_ARB_ALGORITHM>RD_PRI_REG</C0_C_RD_WR_ARB_ALGORITHM>}
   puts $mig_prj_file {      <C0_S_AXI_ADDR_WIDTH>30</C0_S_AXI_ADDR_WIDTH>}
   puts $mig_prj_file {      <C0_S_AXI_DATA_WIDTH>256</C0_S_AXI_DATA_WIDTH>}
   puts $mig_prj_file {      <C0_S_AXI_ID_WIDTH>2</C0_S_AXI_ID_WIDTH>}
   puts $mig_prj_file {      <C0_S_AXI_SUPPORTS_NARROW_BURST>1</C0_S_AXI_SUPPORTS_NARROW_BURST>}
   puts $mig_prj_file {    </AXIParameters>}
   puts $mig_prj_file {  </Controller>}
   puts $mig_prj_file {</Project>}

   close $mig_prj_file
}
# End of write_mig_file_SoC_mig_7series_0_0()



  
# Hierarchical cell: eth_0
proc create_hier_cell_eth_0 { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_eth_0() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S_AXI_LITE

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M_AXI_SG

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 s_axi

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:rgmii_rtl:1.0 eth_rgmii

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:mdio_rtl:1.0 eth_mdio_mdc


  # Create pins
  create_bd_pin -dir I -type clk m_axi_sg_aclk
  create_bd_pin -dir O -type intr mm2s_introut
  create_bd_pin -dir O -type intr s2mm_introut
  create_bd_pin -dir I -type rst s_axi_lite_resetn
  create_bd_pin -dir I -type clk gtx_clk
  create_bd_pin -dir I -type clk ref_clk
  create_bd_pin -dir I -type rst axi_resetn
  create_bd_pin -dir O -from 0 -to 0 -type rst phy_reset_out
  create_bd_pin -dir O -type intr mac_irq

  # Create instance: axi_dma_0, and set properties
  set axi_dma_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dma:7.1 axi_dma_0 ]
  set_property -dict [list \
    CONFIG.c_addr_width {64} \
    CONFIG.c_include_mm2s_dre {1} \
    CONFIG.c_include_s2mm_dre {1} \
    CONFIG.c_m_axi_mm2s_data_width {64} \
    CONFIG.c_m_axi_s2mm_data_width {64} \
    CONFIG.c_m_axis_mm2s_tdata_width {32} \
    CONFIG.c_mm2s_burst_size {16} \
    CONFIG.c_s_axis_s2mm_tdata_width {32} \
    CONFIG.c_single_interface {1} \
  ] $axi_dma_0


  # Create instance: axi_ethernet_0, and set properties
  set axi_ethernet_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_ethernet:7.2 axi_ethernet_0 ]
  set_property -dict [list \
    CONFIG.ETHERNET_BOARD_INTERFACE {eth_rgmii} \
    CONFIG.MDIO_BOARD_INTERFACE {eth_mdio_mdc} \
    CONFIG.PHYRST_BOARD_INTERFACE {phy_reset_out} \
    CONFIG.RXCSUM {Full} \
    CONFIG.TXCSUM {Full} \
    CONFIG.axiliteclkrate {50} \
    CONFIG.axisclkrate {50} \
  ] $axi_ethernet_0


  # Create interface connections
  connect_bd_intf_net -intf_net Conn1 [get_bd_intf_pins axi_ethernet_0/rgmii] [get_bd_intf_pins eth_rgmii]
  connect_bd_intf_net -intf_net Conn2 [get_bd_intf_pins axi_ethernet_0/mdio] [get_bd_intf_pins eth_mdio_mdc]
  connect_bd_intf_net -intf_net axi_dma_0_M_AXI [get_bd_intf_pins M_AXI] [get_bd_intf_pins axi_dma_0/M_AXI]
  connect_bd_intf_net -intf_net axi_dma_0_M_AXIS_CNTRL [get_bd_intf_pins axi_ethernet_0/s_axis_txc] [get_bd_intf_pins axi_dma_0/M_AXIS_CNTRL]
  connect_bd_intf_net -intf_net axi_dma_0_M_AXIS_MM2S [get_bd_intf_pins axi_ethernet_0/s_axis_txd] [get_bd_intf_pins axi_dma_0/M_AXIS_MM2S]
  connect_bd_intf_net -intf_net axi_dma_0_M_AXI_SG [get_bd_intf_pins M_AXI_SG] [get_bd_intf_pins axi_dma_0/M_AXI_SG]
  connect_bd_intf_net -intf_net axi_ethernet_0_m_axis_rxd [get_bd_intf_pins axi_ethernet_0/m_axis_rxd] [get_bd_intf_pins axi_dma_0/S_AXIS_S2MM]
  connect_bd_intf_net -intf_net axi_ethernet_0_m_axis_rxs [get_bd_intf_pins axi_ethernet_0/m_axis_rxs] [get_bd_intf_pins axi_dma_0/S_AXIS_STS]
  connect_bd_intf_net -intf_net axi_interconnect_0_M02_AXI [get_bd_intf_pins S_AXI_LITE] [get_bd_intf_pins axi_dma_0/S_AXI_LITE]
  connect_bd_intf_net -intf_net s_axi_1 [get_bd_intf_pins s_axi] [get_bd_intf_pins axi_ethernet_0/s_axi]

  # Create port connections
  connect_bd_net -net axi_dma_0_mm2s_cntrl_reset_out_n  [get_bd_pins axi_dma_0/mm2s_cntrl_reset_out_n] \
  [get_bd_pins axi_ethernet_0/axi_txc_arstn]
  connect_bd_net -net axi_dma_0_mm2s_introut  [get_bd_pins axi_dma_0/mm2s_introut] \
  [get_bd_pins mm2s_introut]
  connect_bd_net -net axi_dma_0_mm2s_prmry_reset_out_n  [get_bd_pins axi_dma_0/mm2s_prmry_reset_out_n] \
  [get_bd_pins axi_ethernet_0/axi_txd_arstn]
  connect_bd_net -net axi_dma_0_s2mm_introut  [get_bd_pins axi_dma_0/s2mm_introut] \
  [get_bd_pins s2mm_introut]
  connect_bd_net -net axi_dma_0_s2mm_prmry_reset_out_n  [get_bd_pins axi_dma_0/s2mm_prmry_reset_out_n] \
  [get_bd_pins axi_ethernet_0/axi_rxd_arstn]
  connect_bd_net -net axi_dma_0_s2mm_sts_reset_out_n  [get_bd_pins axi_dma_0/s2mm_sts_reset_out_n] \
  [get_bd_pins axi_ethernet_0/axi_rxs_arstn]
  connect_bd_net -net axi_ethernet_0_interrupt  [get_bd_pins axi_ethernet_0/interrupt] \
  [get_bd_pins mac_irq]
  connect_bd_net -net axi_ethernet_0_phy_rst_n1  [get_bd_pins axi_ethernet_0/phy_rst_n] \
  [get_bd_pins phy_reset_out]
  connect_bd_net -net axi_resetn_1  [get_bd_pins axi_resetn] \
  [get_bd_pins axi_dma_0/axi_resetn]
  connect_bd_net -net clk_wiz_0_clk_out1  [get_bd_pins m_axi_sg_aclk] \
  [get_bd_pins axi_dma_0/m_axi_sg_aclk] \
  [get_bd_pins axi_dma_0/m_axi_mm2s_aclk] \
  [get_bd_pins axi_dma_0/m_axi_s2mm_aclk] \
  [get_bd_pins axi_dma_0/s_axi_lite_aclk] \
  [get_bd_pins axi_ethernet_0/s_axi_lite_clk] \
  [get_bd_pins axi_ethernet_0/axis_clk]
  connect_bd_net -net gtx_clk_1  [get_bd_pins gtx_clk] \
  [get_bd_pins axi_ethernet_0/gtx_clk]
  connect_bd_net -net ref_clk_1  [get_bd_pins ref_clk] \
  [get_bd_pins axi_ethernet_0/ref_clk]
  connect_bd_net -net s_axi_lite_resetn_1  [get_bd_pins s_axi_lite_resetn] \
  [get_bd_pins axi_ethernet_0/s_axi_lite_resetn]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  
# Hierarchical cell: northbridge
proc create_hier_cell_northbridge { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_northbridge() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 CPU_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 ETH_DMA_AXI_0

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M00_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M01_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 ETH_DMA_AXI_1

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M02_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M03_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M05_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M07_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M08_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M09_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M10_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M04_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M06_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 DEBUG_MODULE_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M12_AXI

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 M13_AXI


  # Create pins
  create_bd_pin -dir I -type clk peripheral_aclk
  create_bd_pin -dir I -from 5 -to 0 cpu_atop_in
  create_bd_pin -dir I -type clk mig_aclk
  create_bd_pin -dir I -type rst mig_aresetn
  create_bd_pin -dir I -from 1 -to 0 -type intr dummy_irq_in
  create_bd_pin -dir I -type clk clk_cpu
  create_bd_pin -dir I -type rst cpu_interconnect_aresetn
  create_bd_pin -dir I -type rst cpu_peripheral_aresetn
  create_bd_pin -dir I -from 0 -to 0 ndmreset

  # Create instance: axi_interconnect_0, and set properties
  set axi_interconnect_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_0 ]
  set_property -dict [list \
    CONFIG.ENABLE_ADVANCED_OPTIONS {1} \
    CONFIG.ENABLE_PROTOCOL_CHECKERS {0} \
    CONFIG.NUM_MI {13} \
    CONFIG.NUM_SI {4} \
    CONFIG.S00_HAS_DATA_FIFO {0} \
    CONFIG.S01_HAS_DATA_FIFO {0} \
    CONFIG.S02_HAS_DATA_FIFO {0} \
    CONFIG.S03_HAS_DATA_FIFO {0} \
    CONFIG.S04_HAS_DATA_FIFO {2} \
    CONFIG.STRATEGY {0} \
    CONFIG.SYNCHRONIZATION_STAGES {2} \
  ] $axi_interconnect_0


  # Create instance: axi_riscv_atomics_wrapper_0, and set properties
  set block_name axi_riscv_atomics_wrapper_verilog
  set block_cell_name axi_riscv_atomics_wrapper_0
  if { [catch {set axi_riscv_atomics_wrapper_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $axi_riscv_atomics_wrapper_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property CONFIG.AXI_ID_WIDTH {4} $axi_riscv_atomics_wrapper_0


  # Create instance: axidebug_0, and set properties
  set axidebug_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:system_ila:1.1 axidebug_0 ]
  set_property -dict [list \
    CONFIG.C_ADV_TRIGGER {true} \
    CONFIG.C_EN_STRG_QUAL {1} \
    CONFIG.C_MON_TYPE {MIX} \
    CONFIG.C_NUM_MONITOR_SLOTS {2} \
    CONFIG.C_NUM_OF_PROBES {6} \
    CONFIG.C_SLOT {1} \
    CONFIG.C_SLOT_0_APC_EN {1} \
    CONFIG.C_SLOT_0_APC_STS_EN {1} \
    CONFIG.C_SLOT_1_APC_EN {1} \
    CONFIG.C_SLOT_1_APC_STS_EN {1} \
  ] $axidebug_0


  # Create interface connections
  connect_bd_intf_net -intf_net CPU_AXI_1 [get_bd_intf_pins CPU_AXI] [get_bd_intf_pins axi_riscv_atomics_wrapper_0/s_axi_in]
  connect_bd_intf_net -intf_net [get_bd_intf_nets CPU_AXI_1] [get_bd_intf_pins CPU_AXI] [get_bd_intf_pins axidebug_0/SLOT_0_AXI]
  connect_bd_intf_net -intf_net Conn3 [get_bd_intf_pins axi_interconnect_0/M04_AXI] [get_bd_intf_pins M04_AXI]
  connect_bd_intf_net -intf_net Conn4 [get_bd_intf_pins axi_interconnect_0/M06_AXI] [get_bd_intf_pins M06_AXI]
  connect_bd_intf_net -intf_net DEBUG_MODULE_AXI_1 [get_bd_intf_pins DEBUG_MODULE_AXI] [get_bd_intf_pins axi_interconnect_0/S03_AXI]
  connect_bd_intf_net -intf_net ETH_DMA_AXI_0_1 [get_bd_intf_pins ETH_DMA_AXI_0] [get_bd_intf_pins axi_interconnect_0/S00_AXI]
  connect_bd_intf_net -intf_net ETH_DMA_AXI_1_1 [get_bd_intf_pins ETH_DMA_AXI_1] [get_bd_intf_pins axi_interconnect_0/S01_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M00_AXI [get_bd_intf_pins M00_AXI] [get_bd_intf_pins axi_interconnect_0/M00_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M01_AXI [get_bd_intf_pins M01_AXI] [get_bd_intf_pins axi_interconnect_0/M01_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M02_AXI [get_bd_intf_pins M02_AXI] [get_bd_intf_pins axi_interconnect_0/M02_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M03_AXI [get_bd_intf_pins M03_AXI] [get_bd_intf_pins axi_interconnect_0/M03_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M05_AXI [get_bd_intf_pins M05_AXI] [get_bd_intf_pins axi_interconnect_0/M05_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M07_AXI [get_bd_intf_pins M07_AXI] [get_bd_intf_pins axi_interconnect_0/M07_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M08_AXI [get_bd_intf_pins M08_AXI] [get_bd_intf_pins axi_interconnect_0/M08_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M09_AXI [get_bd_intf_pins M09_AXI] [get_bd_intf_pins axi_interconnect_0/M09_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M10_AXI [get_bd_intf_pins M10_AXI] [get_bd_intf_pins axi_interconnect_0/M10_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M11_AXI [get_bd_intf_pins M12_AXI] [get_bd_intf_pins axi_interconnect_0/M11_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M12_AXI [get_bd_intf_pins M13_AXI] [get_bd_intf_pins axi_interconnect_0/M12_AXI]
  connect_bd_intf_net -intf_net axi_riscv_atomics_wrapper_0_m_axi_out [get_bd_intf_pins axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_intf_pins axi_interconnect_0/S02_AXI]
  connect_bd_intf_net -intf_net [get_bd_intf_nets axi_riscv_atomics_wrapper_0_m_axi_out] [get_bd_intf_pins axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_intf_pins axidebug_0/SLOT_1_AXI]

  # Create port connections
  connect_bd_net -net S02_ARESETN_1  [get_bd_pins cpu_peripheral_aresetn] \
  [get_bd_pins axidebug_0/resetn] \
  [get_bd_pins axidebug_0/probe4]
  connect_bd_net -net S02_ARESETN_2  [get_bd_pins cpu_interconnect_aresetn] \
  [get_bd_pins axi_interconnect_0/S02_ARESETN] \
  [get_bd_pins axi_riscv_atomics_wrapper_0/aresetn] \
  [get_bd_pins axidebug_0/probe3] \
  [get_bd_pins axi_interconnect_0/ARESETN] \
  [get_bd_pins axi_interconnect_0/S00_ARESETN] \
  [get_bd_pins axi_interconnect_0/S01_ARESETN] \
  [get_bd_pins axi_interconnect_0/M01_ARESETN] \
  [get_bd_pins axi_interconnect_0/M02_ARESETN] \
  [get_bd_pins axi_interconnect_0/M03_ARESETN] \
  [get_bd_pins axi_interconnect_0/M04_ARESETN] \
  [get_bd_pins axi_interconnect_0/M05_ARESETN] \
  [get_bd_pins axi_interconnect_0/M06_ARESETN] \
  [get_bd_pins axi_interconnect_0/M07_ARESETN] \
  [get_bd_pins axi_interconnect_0/M08_ARESETN] \
  [get_bd_pins axi_interconnect_0/M10_ARESETN] \
  [get_bd_pins axi_interconnect_0/M09_ARESETN] \
  [get_bd_pins axi_interconnect_0/S03_ARESETN] \
  [get_bd_pins axi_interconnect_0/M11_ARESETN]
  connect_bd_net -net aclk1_1  [get_bd_pins clk_cpu] \
  [get_bd_pins axi_interconnect_0/S02_ACLK] \
  [get_bd_pins axi_riscv_atomics_wrapper_0/CLK] \
  [get_bd_pins axidebug_0/clk]
  connect_bd_net -net axi_riscv_atomics_wrapper_0_m_axi_out_awatop  [get_bd_pins cpu_atop_in] \
  [get_bd_pins axidebug_0/probe0] \
  [get_bd_pins axi_riscv_atomics_wrapper_0/s_axi_in_awatop] \
  [get_bd_pins axidebug_0/probe1]
  connect_bd_net -net axi_riscv_atomics_wrapper_0_m_axi_out_awatop1  [get_bd_pins axi_riscv_atomics_wrapper_0/m_axi_out_awatop] \
  [get_bd_pins axidebug_0/probe2]
  connect_bd_net -net clk_wiz_0_clk_out1  [get_bd_pins peripheral_aclk] \
  [get_bd_pins axi_interconnect_0/ACLK] \
  [get_bd_pins axi_interconnect_0/S00_ACLK] \
  [get_bd_pins axi_interconnect_0/M01_ACLK] \
  [get_bd_pins axi_interconnect_0/S01_ACLK] \
  [get_bd_pins axi_interconnect_0/M02_ACLK] \
  [get_bd_pins axi_interconnect_0/M03_ACLK] \
  [get_bd_pins axi_interconnect_0/M04_ACLK] \
  [get_bd_pins axi_interconnect_0/M05_ACLK] \
  [get_bd_pins axi_interconnect_0/M06_ACLK] \
  [get_bd_pins axi_interconnect_0/M07_ACLK] \
  [get_bd_pins axi_interconnect_0/M08_ACLK] \
  [get_bd_pins axi_interconnect_0/M09_ACLK] \
  [get_bd_pins axi_interconnect_0/M10_ACLK] \
  [get_bd_pins axi_interconnect_0/S03_ACLK] \
  [get_bd_pins axi_interconnect_0/M11_ACLK]
  connect_bd_net -net dummy_irq_in_1  [get_bd_pins dummy_irq_in] \
  [get_bd_pins axi_riscv_atomics_wrapper_0/dummy_irq_in]
  connect_bd_net -net mig_7series_0_ui_clk  [get_bd_pins mig_aclk] \
  [get_bd_pins axi_interconnect_0/M00_ACLK] \
  [get_bd_pins axi_interconnect_0/M12_ACLK]
  connect_bd_net -net probe5_1  [get_bd_pins ndmreset] \
  [get_bd_pins axidebug_0/probe5]
  connect_bd_net -net reset_polarity_conv_Res  [get_bd_pins mig_aresetn] \
  [get_bd_pins axi_interconnect_0/M00_ARESETN] \
  [get_bd_pins axi_interconnect_0/M12_ARESETN]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set ja [ create_bd_intf_port -mode Master -vlnv digilentinc.com:interface:pmod_rtl:1.0 ja ]

  set audio_codec_iic [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:iic_rtl:1.0 audio_codec_iic ]

  set sys_diff_clock [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 sys_diff_clock ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {200000000} \
   ] $sys_diff_clock

  set usb_uart [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:uart_rtl:1.0 usb_uart ]

  set ddr3_sdram [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 ddr3_sdram ]

  set eth_rgmii [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:rgmii_rtl:1.0 eth_rgmii ]

  set eth_mdio_mdc [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:mdio_rtl:1.0 eth_mdio_mdc ]


  # Create ports
  set reset [ create_bd_port -dir I -type rst reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_LOW} \
 ] $reset
  set spi_clk_o [ create_bd_port -dir O -type clk spi_clk_o ]
  set spi_ss [ create_bd_port -dir O -from 0 -to 0 -type data spi_ss ]
  set spi_mosi [ create_bd_port -dir O -type data spi_mosi ]
  set spi_miso [ create_bd_port -dir I -type data spi_miso ]
  set jtag_tdo [ create_bd_port -dir O -type data jtag_tdo ]
  set jtag_tck [ create_bd_port -dir I -type data jtag_tck ]
  set jtag_tms [ create_bd_port -dir I -type data jtag_tms ]
  set jtag_tdi [ create_bd_port -dir I -type data jtag_tdi ]
  set jtag_trst_n [ create_bd_port -dir I -type data jtag_trst_n ]
  set fan_pwm [ create_bd_port -dir O -type data fan_pwm ]
  set fan_tach [ create_bd_port -dir I -type data fan_tach ]
  set phy_reset_out [ create_bd_port -dir O -from 0 -to 0 -type rst phy_reset_out ]

  # Create instance: axi_bram_ctrl_0, and set properties
  set axi_bram_ctrl_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl:4.1 axi_bram_ctrl_0 ]
  set_property -dict [list \
    CONFIG.DATA_WIDTH {64} \
    CONFIG.SINGLE_PORT_BRAM {1} \
  ] $axi_bram_ctrl_0


  # Create instance: tieoff_1, and set properties
  set tieoff_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 tieoff_1 ]
  set_property CONFIG.CONST_VAL {0} $tieoff_1


  # Create instance: axi_uart16550_0, and set properties
  set axi_uart16550_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_uart16550:2.0 axi_uart16550_0 ]
  set_property -dict [list \
    CONFIG.UART_BOARD_INTERFACE {usb_uart} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $axi_uart16550_0


  # Create instance: peripherals_clockgen, and set properties
  set peripherals_clockgen [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 peripherals_clockgen ]
  set_property -dict [list \
    CONFIG.CLKOUT1_DRIVES {BUFGCE} \
    CONFIG.CLKOUT1_JITTER {95.782} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {125} \
    CONFIG.CLKOUT2_DRIVES {BUFGCE} \
    CONFIG.CLKOUT2_JITTER {87.254} \
    CONFIG.CLKOUT2_PHASE_ERROR {79.885} \
    CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {200.000} \
    CONFIG.CLKOUT2_USED {true} \
    CONFIG.CLKOUT3_DRIVES {BUFGCE} \
    CONFIG.CLKOUT3_JITTER {114.996} \
    CONFIG.CLKOUT3_PHASE_ERROR {79.885} \
    CONFIG.CLKOUT3_REQUESTED_OUT_FREQ {50} \
    CONFIG.CLKOUT3_USED {true} \
    CONFIG.CLKOUT4_DRIVES {BUFGCE} \
    CONFIG.CLKOUT5_DRIVES {BUFGCE} \
    CONFIG.CLKOUT6_DRIVES {BUFGCE} \
    CONFIG.CLKOUT7_DRIVES {BUFGCE} \
    CONFIG.CLK_IN1_BOARD_INTERFACE {Custom} \
    CONFIG.CLK_OUT1_PORT {clk_125} \
    CONFIG.CLK_OUT2_PORT {clk_200} \
    CONFIG.CLK_OUT3_PORT {clk_50} \
    CONFIG.FEEDBACK_SOURCE {FDBK_AUTO} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F {8.000} \
    CONFIG.MMCM_CLKOUT1_DIVIDE {5} \
    CONFIG.MMCM_CLKOUT2_DIVIDE {20} \
    CONFIG.NUM_OUT_CLKS {3} \
    CONFIG.PRIM_SOURCE {No_buffer} \
    CONFIG.RESET_PORT {resetn} \
    CONFIG.RESET_TYPE {ACTIVE_LOW} \
    CONFIG.SECONDARY_SOURCE {Single_ended_clock_capable_pin} \
    CONFIG.USE_BOARD_FLOW {true} \
    CONFIG.USE_LOCKED {true} \
    CONFIG.USE_PHASE_ALIGNMENT {false} \
    CONFIG.USE_SAFE_CLOCK_STARTUP {true} \
  ] $peripherals_clockgen


  # Create instance: axi_quad_spi_0, and set properties
  set axi_quad_spi_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_quad_spi:3.2 axi_quad_spi_0 ]
  set_property -dict [list \
    CONFIG.Async_Clk {0} \
    CONFIG.C_FIFO_DEPTH {256} \
    CONFIG.C_SCK_RATIO {4} \
    CONFIG.C_TYPE_OF_AXI4_INTERFACE {1} \
    CONFIG.C_USE_STARTUP {0} \
    CONFIG.QSPI_BOARD_INTERFACE {Custom} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $axi_quad_spi_0


  # Create instance: PmodGPIO_0, and set properties
  set PmodGPIO_0 [ create_bd_cell -type ip -vlnv digilentinc.com:IP:PmodGPIO:1.0 PmodGPIO_0 ]
  set_property -dict [list \
    CONFIG.PMOD {ja} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $PmodGPIO_0


  # Create instance: axi_iic_0, and set properties
  set axi_iic_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_iic:2.1 axi_iic_0 ]
  set_property -dict [list \
    CONFIG.IIC_BOARD_INTERFACE {audio_codec_iic} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $axi_iic_0


  # Create instance: reset_polarity_conv, and set properties
  set reset_polarity_conv [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 reset_polarity_conv ]
  set_property -dict [list \
    CONFIG.C_OPERATION {not} \
    CONFIG.C_SIZE {1} \
  ] $reset_polarity_conv


  # Create instance: bootrom_wrapper_0, and set properties
  set block_name bootrom_wrapper
  set block_cell_name bootrom_wrapper_0
  if { [catch {set bootrom_wrapper_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $bootrom_wrapper_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: ariane_peripherals_0, and set properties
  set block_name ariane_peripherals_wrapper_verilog
  set block_cell_name ariane_peripherals_0
  if { [catch {set ariane_peripherals_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $ariane_peripherals_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property -dict [list \
    CONFIG.AXI_DATA_WIDTH {64} \
    CONFIG.AXI_ID_WIDTH {14} \
    CONFIG.NUMBER_INTERRUPTS {6} \
  ] $ariane_peripherals_0


  # Create instance: atop_tieoff_0, and set properties
  set atop_tieoff_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 atop_tieoff_0 ]
  set_property -dict [list \
    CONFIG.CONST_VAL {0} \
    CONFIG.CONST_WIDTH {6} \
  ] $atop_tieoff_0


  # Create instance: irqconcat, and set properties
  set irqconcat [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat:2.1 irqconcat ]
  set_property CONFIG.NUM_PORTS {6} $irqconcat


  # Create instance: cpu_0, and set properties
  set block_name cva6_wrapper_verilog
  set block_cell_name cpu_0
  if { [catch {set cpu_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $cpu_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property CONFIG.AXI_ID_WIDTH {4} $cpu_0


  # Create instance: clint_0, and set properties
  set block_name clint_wrapper_verilog
  set block_cell_name clint_0
  if { [catch {set clint_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $clint_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property CONFIG.AXI_ID_WIDTH {14} $clint_0


  # Create instance: northbridge
  create_hier_cell_northbridge [current_bd_instance .] northbridge

  # Create instance: eth_0
  create_hier_cell_eth_0 [current_bd_instance .] eth_0

  # Create instance: cpu_reset_gen, and set properties
  set cpu_reset_gen [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 cpu_reset_gen ]

  # Create instance: mig_7series_0, and set properties
  set mig_7series_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:mig_7series:4.2 mig_7series_0 ]

  # Generate the PRJ File for MIG
  set str_mig_folder [get_property IP_DIR [ get_ips [ get_property CONFIG.Component_Name $mig_7series_0 ] ] ]
  set str_mig_file_name mig_b.prj
  set str_mig_file_path ${str_mig_folder}/${str_mig_file_name}
  write_mig_file_SoC_mig_7series_0_0 $str_mig_file_path

  set_property -dict [list \
    CONFIG.BOARD_MIG_PARAM {ddr3_sdram} \
    CONFIG.RESET_BOARD_INTERFACE {Custom} \
    CONFIG.XML_INPUT_FILE {mig_b.prj} \
  ] $mig_7series_0


  # Create instance: cpu_debug, and set properties
  set block_name debug_module_wrapper_verilog
  set block_cell_name cpu_debug
  if { [catch {set cpu_debug [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $cpu_debug eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property CONFIG.AXI_ID_WIDTH {4} $cpu_debug


  # Create instance: atop_tieoff, and set properties
  set atop_tieoff [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 atop_tieoff ]
  set_property -dict [list \
    CONFIG.CONST_VAL {0} \
    CONFIG.CONST_WIDTH {6} \
  ] $atop_tieoff


  # Create instance: memory_reset_synch, and set properties
  set memory_reset_synch [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 memory_reset_synch ]

  # Create instance: axi_fan_control_0, and set properties
  set block_name axi_fan_control
  set block_cell_name axi_fan_control_0
  if { [catch {set axi_fan_control_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $axi_fan_control_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
    set_property -dict [list \
    CONFIG.DEVICE_TYPE {1} \
    CONFIG.TEMP_00_H {50} \
    CONFIG.TEMP_25_H {65} \
    CONFIG.TEMP_25_L {55} \
    CONFIG.TEMP_50_H {75} \
    CONFIG.TEMP_50_L {70} \
    CONFIG.TEMP_INPUT_BITS {12} \
  ] $axi_fan_control_0


  # Create instance: xadc_wiz_0, and set properties
  set xadc_wiz_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xadc_wiz:3.3 xadc_wiz_0 ]
  set_property -dict [list \
    CONFIG.ADC_CONVERSION_RATE {962} \
    CONFIG.CHANNEL_ENABLE_TEMPERATURE {false} \
    CONFIG.CHANNEL_ENABLE_VP_VN {false} \
    CONFIG.DCLK_FREQUENCY {225} \
    CONFIG.ENABLE_AXI4STREAM {true} \
    CONFIG.ENABLE_DCLK {true} \
    CONFIG.ENABLE_DRP {false} \
    CONFIG.ENABLE_JTAG_ARBITER {false} \
    CONFIG.ENABLE_RESET {false} \
    CONFIG.ENABLE_TEMP_BUS {true} \
    CONFIG.EXTERNAL_MUX_CHANNEL {VP_VN} \
    CONFIG.INTERFACE_SELECTION {None} \
    CONFIG.SEQUENCER_MODE {Off} \
    CONFIG.SINGLE_CHANNEL_ACQUISITION_TIME {false} \
    CONFIG.SINGLE_CHANNEL_SELECTION {TEMPERATURE} \
    CONFIG.TIMING_MODE {Continuous} \
    CONFIG.XADC_STARUP_SELECTION {single_channel} \
  ] $xadc_wiz_0


  # Create instance: tready_always_ready, and set properties
  set tready_always_ready [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 tready_always_ready ]

  # Create instance: interrupt_sync_0, and set properties
  set block_name interrupt_synchronizer
  set block_cell_name interrupt_sync_0
  if { [catch {set interrupt_sync_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $interrupt_sync_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: irq_ila, and set properties
  set irq_ila [ create_bd_cell -type ip -vlnv xilinx.com:ip:system_ila:1.1 irq_ila ]
  set_property -dict [list \
    CONFIG.C_MON_TYPE {NATIVE} \
    CONFIG.C_NUM_OF_PROBES {6} \
  ] $irq_ila


  # Create interface connections
  connect_bd_intf_net -intf_net ETH_DMA_AXI_0_1 [get_bd_intf_pins northbridge/ETH_DMA_AXI_0] [get_bd_intf_pins eth_0/M_AXI_SG]
  connect_bd_intf_net -intf_net PmodGPIO_0_Pmod_out [get_bd_intf_ports ja] [get_bd_intf_pins PmodGPIO_0/Pmod_out]
  connect_bd_intf_net -intf_net axi_iic_0_IIC [get_bd_intf_ports audio_codec_iic] [get_bd_intf_pins axi_iic_0/IIC]
  connect_bd_intf_net -intf_net axi_interconnect_0_M01_AXI [get_bd_intf_pins axi_uart16550_0/S_AXI] [get_bd_intf_pins northbridge/M01_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M02_AXI [get_bd_intf_pins northbridge/M02_AXI] [get_bd_intf_pins eth_0/S_AXI_LITE]
  connect_bd_intf_net -intf_net axi_interconnect_0_M03_AXI [get_bd_intf_pins northbridge/M03_AXI] [get_bd_intf_pins eth_0/s_axi]
  connect_bd_intf_net -intf_net axi_interconnect_0_M04_AXI [get_bd_intf_pins axi_bram_ctrl_0/S_AXI] [get_bd_intf_pins northbridge/M04_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M05_AXI [get_bd_intf_pins northbridge/M05_AXI] [get_bd_intf_pins clint_0/s_axi_clint]
  connect_bd_intf_net -intf_net axi_interconnect_0_M07_AXI [get_bd_intf_pins PmodGPIO_0/AXI_LITE_GPIO] [get_bd_intf_pins northbridge/M07_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M08_AXI [get_bd_intf_pins axi_iic_0/S_AXI] [get_bd_intf_pins northbridge/M08_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M09_AXI [get_bd_intf_pins northbridge/M09_AXI] [get_bd_intf_pins ariane_peripherals_0/s_axi_plic]
  connect_bd_intf_net -intf_net axi_interconnect_0_M10_AXI [get_bd_intf_pins northbridge/M10_AXI] [get_bd_intf_pins ariane_peripherals_0/s_axi_timer]
  connect_bd_intf_net -intf_net axi_uart16550_0_UART [get_bd_intf_ports usb_uart] [get_bd_intf_pins axi_uart16550_0/UART]
  connect_bd_intf_net -intf_net cpu_0_m_axi_cpu [get_bd_intf_pins cpu_0/m_axi_cpu] [get_bd_intf_pins northbridge/CPU_AXI]
  connect_bd_intf_net -intf_net cpu_debug_m_axi_dmi_jtag [get_bd_intf_pins cpu_debug/m_axi_dmi_jtag] [get_bd_intf_pins northbridge/DEBUG_MODULE_AXI]
  connect_bd_intf_net -intf_net eth_0_M_AXI [get_bd_intf_pins eth_0/M_AXI] [get_bd_intf_pins northbridge/ETH_DMA_AXI_1]
  connect_bd_intf_net -intf_net eth_0_eth_mdio_mdc [get_bd_intf_ports eth_mdio_mdc] [get_bd_intf_pins eth_0/eth_mdio_mdc]
  connect_bd_intf_net -intf_net eth_0_eth_rgmii [get_bd_intf_ports eth_rgmii] [get_bd_intf_pins eth_0/eth_rgmii]
  connect_bd_intf_net -intf_net mig_7series_0_DDR3 [get_bd_intf_ports ddr3_sdram] [get_bd_intf_pins mig_7series_0/DDR3]
  connect_bd_intf_net -intf_net northbridge_M00_AXI [get_bd_intf_pins northbridge/M00_AXI] [get_bd_intf_pins mig_7series_0/S_AXI]
  connect_bd_intf_net -intf_net northbridge_M06_AXI [get_bd_intf_pins axi_quad_spi_0/AXI_FULL] [get_bd_intf_pins northbridge/M06_AXI]
  connect_bd_intf_net -intf_net northbridge_M12_AXI [get_bd_intf_pins cpu_debug/s_axi_dmi_jtag] [get_bd_intf_pins northbridge/M12_AXI]
  connect_bd_intf_net -intf_net northbridge_M13_AXI [get_bd_intf_pins axi_fan_control_0/s_axi] [get_bd_intf_pins northbridge/M13_AXI]
  connect_bd_intf_net -intf_net sys_diff_clock_1 [get_bd_intf_ports sys_diff_clock] [get_bd_intf_pins mig_7series_0/SYS_CLK]

  # Create port connections
  connect_bd_net -net ariane_peripherals_0_irq_out  [get_bd_pins ariane_peripherals_0/irq_out] \
  [get_bd_pins northbridge/dummy_irq_in] \
  [get_bd_pins irq_ila/probe0] \
  [get_bd_pins cpu_0/irqs_in]
  connect_bd_net -net atop_tieoff_0_dout  [get_bd_pins atop_tieoff_0/dout] \
  [get_bd_pins clint_0/s_axi_clint_awatop] \
  [get_bd_pins ariane_peripherals_0/s_axi_plic_awatop] \
  [get_bd_pins ariane_peripherals_0/s_axi_timer_awatop]
  connect_bd_net -net atop_tieoff_dout  [get_bd_pins atop_tieoff/dout] \
  [get_bd_pins cpu_debug/s_axi_dmi_jtag_awatop]
  connect_bd_net -net axi_bram_ctrl_0_bram_addr_a  [get_bd_pins axi_bram_ctrl_0/bram_addr_a] \
  [get_bd_pins bootrom_wrapper_0/addr_i]
  connect_bd_net -net axi_bram_ctrl_0_bram_clk_a  [get_bd_pins axi_bram_ctrl_0/bram_clk_a] \
  [get_bd_pins bootrom_wrapper_0/clk_i]
  connect_bd_net -net axi_bram_ctrl_0_bram_en_a  [get_bd_pins axi_bram_ctrl_0/bram_en_a] \
  [get_bd_pins bootrom_wrapper_0/req_i]
  connect_bd_net -net axi_dma_0_mm2s_introut  [get_bd_pins eth_0/mm2s_introut] \
  [get_bd_pins irqconcat/In0]
  connect_bd_net -net axi_dma_0_s2mm_introut  [get_bd_pins eth_0/s2mm_introut] \
  [get_bd_pins irqconcat/In1]
  connect_bd_net -net axi_fan_control_0_irq  [get_bd_pins axi_fan_control_0/irq] \
  [get_bd_pins interrupt_sync_0/irq_in]
  connect_bd_net -net axi_fan_control_0_pwm  [get_bd_pins axi_fan_control_0/pwm] \
  [get_bd_ports fan_pwm]
  connect_bd_net -net axi_quad_spi_0_io0_o  [get_bd_pins axi_quad_spi_0/io0_o] \
  [get_bd_ports spi_mosi]
  connect_bd_net -net axi_quad_spi_0_ip2intc_irpt  [get_bd_pins axi_quad_spi_0/ip2intc_irpt] \
  [get_bd_pins irqconcat/In2]
  connect_bd_net -net axi_quad_spi_0_sck_o  [get_bd_pins axi_quad_spi_0/sck_o] \
  [get_bd_ports spi_clk_o]
  connect_bd_net -net axi_quad_spi_0_ss_o  [get_bd_pins axi_quad_spi_0/ss_o] \
  [get_bd_ports spi_ss]
  connect_bd_net -net axi_uart16550_0_ip2intc_irpt  [get_bd_pins axi_uart16550_0/ip2intc_irpt] \
  [get_bd_pins irqconcat/In3]
  connect_bd_net -net bootrom_wrapper_0_rdata_o  [get_bd_pins bootrom_wrapper_0/rdata_o] \
  [get_bd_pins axi_bram_ctrl_0/bram_rddata_a]
  connect_bd_net -net clint_0_ipi_o  [get_bd_pins clint_0/ipi_o] \
  [get_bd_pins irq_ila/probe1] \
  [get_bd_pins cpu_0/ipi_in]
  connect_bd_net -net clint_0_timer_irq_o  [get_bd_pins clint_0/timer_irq_o] \
  [get_bd_pins irq_ila/probe2] \
  [get_bd_pins cpu_0/timer_irq_i]
  connect_bd_net -net clk_wiz_0_clk_out1  [get_bd_pins peripherals_clockgen/clk_50] \
  [get_bd_pins axi_bram_ctrl_0/s_axi_aclk] \
  [get_bd_pins axi_uart16550_0/s_axi_aclk] \
  [get_bd_pins PmodGPIO_0/s_axi_aclk] \
  [get_bd_pins axi_quad_spi_0/ext_spi_clk] \
  [get_bd_pins axi_iic_0/s_axi_aclk] \
  [get_bd_pins clint_0/aclk] \
  [get_bd_pins northbridge/peripheral_aclk] \
  [get_bd_pins eth_0/m_axi_sg_aclk] \
  [get_bd_pins ariane_peripherals_0/aclk] \
  [get_bd_pins cpu_reset_gen/slowest_sync_clk] \
  [get_bd_pins northbridge/clk_cpu] \
  [get_bd_pins axi_quad_spi_0/s_axi4_aclk] \
  [get_bd_pins cpu_debug/aclk] \
  [get_bd_pins memory_reset_synch/slowest_sync_clk] \
  [get_bd_pins interrupt_sync_0/target_clock] \
  [get_bd_pins irq_ila/clk] \
  [get_bd_pins cpu_0/aclk]
  connect_bd_net -net cpu_0_m_axi_cpu_awatop  [get_bd_pins cpu_0/m_axi_cpu_awatop] \
  [get_bd_pins northbridge/cpu_atop_in]
  connect_bd_net -net cpu_debug_debug_req_irq  [get_bd_pins cpu_debug/debug_req_irq] \
  [get_bd_pins irq_ila/probe3] \
  [get_bd_pins cpu_0/debug_req_irq]
  connect_bd_net -net cpu_debug_jtag_tdo  [get_bd_pins cpu_debug/jtag_tdo] \
  [get_bd_ports jtag_tdo]
  connect_bd_net -net cpu_debug_ndmreset  [get_bd_pins cpu_debug/ndmreset] \
  [get_bd_pins irq_ila/probe5] \
  [get_bd_pins northbridge/ndmreset] \
  [get_bd_pins cpu_reset_gen/ext_reset_in]
  connect_bd_net -net cpu_interconnect_aresetn_1  [get_bd_pins cpu_reset_gen/interconnect_aresetn] \
  [get_bd_pins northbridge/cpu_interconnect_aresetn]
  connect_bd_net -net cpu_reset_gen_peripheral_aresetn  [get_bd_pins cpu_reset_gen/peripheral_aresetn] \
  [get_bd_pins eth_0/axi_resetn] \
  [get_bd_pins eth_0/s_axi_lite_resetn] \
  [get_bd_pins northbridge/cpu_peripheral_aresetn] \
  [get_bd_pins axi_bram_ctrl_0/s_axi_aresetn] \
  [get_bd_pins clint_0/aresetn] \
  [get_bd_pins ariane_peripherals_0/aresetn] \
  [get_bd_pins PmodGPIO_0/s_axi_aresetn] \
  [get_bd_pins axi_quad_spi_0/s_axi4_aresetn] \
  [get_bd_pins axi_uart16550_0/s_axi_aresetn] \
  [get_bd_pins axi_iic_0/s_axi_aresetn] \
  [get_bd_pins interrupt_sync_0/target_resetn] \
  [get_bd_pins cpu_0/aresetn]
  connect_bd_net -net eth_0_mac_irq  [get_bd_pins eth_0/mac_irq] \
  [get_bd_pins irqconcat/In5]
  connect_bd_net -net eth_0_phy_reset_out1  [get_bd_pins eth_0/phy_reset_out] \
  [get_bd_ports phy_reset_out]
  connect_bd_net -net eth_clockgen_clk_125  [get_bd_pins peripherals_clockgen/clk_125] \
  [get_bd_pins eth_0/gtx_clk]
  connect_bd_net -net eth_clockgen_clk_200  [get_bd_pins peripherals_clockgen/clk_200] \
  [get_bd_pins eth_0/ref_clk]
  connect_bd_net -net fan_tach_1  [get_bd_ports fan_tach] \
  [get_bd_pins axi_fan_control_0/tacho]
  connect_bd_net -net interrupt_synchroniz_0_irq_out  [get_bd_pins interrupt_sync_0/irq_out] \
  [get_bd_pins irqconcat/In4]
  connect_bd_net -net irqconcat_dout  [get_bd_pins irqconcat/dout] \
  [get_bd_pins ariane_peripherals_0/irqs_in] \
  [get_bd_pins irq_ila/probe4]
  connect_bd_net -net jtag_tck_1  [get_bd_ports jtag_tck] \
  [get_bd_pins cpu_debug/jtag_tck]
  connect_bd_net -net jtag_tdi_1  [get_bd_ports jtag_tdi] \
  [get_bd_pins cpu_debug/jtag_tdi]
  connect_bd_net -net jtag_tms_1  [get_bd_ports jtag_tms] \
  [get_bd_pins cpu_debug/jtag_tms]
  connect_bd_net -net jtag_trst_n_1  [get_bd_ports jtag_trst_n] \
  [get_bd_pins cpu_debug/jtag_trst_n]
  connect_bd_net -net mig_7series_0_mmcm_locked  [get_bd_pins mig_7series_0/mmcm_locked] \
  [get_bd_pins peripherals_clockgen/resetn]
  connect_bd_net -net mig_7series_0_ui_addn_clk_0  [get_bd_pins mig_7series_0/ui_addn_clk_0] \
  [get_bd_pins peripherals_clockgen/clk_in1]
  connect_bd_net -net mig_7series_0_ui_clk_sync_rst  [get_bd_pins mig_7series_0/ui_clk_sync_rst] \
  [get_bd_pins reset_polarity_conv/Op1] \
  [get_bd_pins memory_reset_synch/ext_reset_in] \
  [get_bd_pins cpu_reset_gen/aux_reset_in]
  connect_bd_net -net mig_aclk_1  [get_bd_pins mig_7series_0/ui_clk] \
  [get_bd_pins northbridge/mig_aclk] \
  [get_bd_pins xadc_wiz_0/m_axis_aclk] \
  [get_bd_pins xadc_wiz_0/s_axis_aclk] \
  [get_bd_pins axi_fan_control_0/s_axi_aclk] \
  [get_bd_pins interrupt_sync_0/source_clock]
  connect_bd_net -net proc_sys_reset_0_peripheral_aresetn  [get_bd_pins memory_reset_synch/peripheral_aresetn] \
  [get_bd_pins cpu_debug/aresetn]
  connect_bd_net -net reset_2  [get_bd_ports reset] \
  [get_bd_pins mig_7series_0/sys_rst]
  connect_bd_net -net reset_polarity_conv_Res  [get_bd_pins reset_polarity_conv/Res] \
  [get_bd_pins northbridge/mig_aresetn] \
  [get_bd_pins mig_7series_0/aresetn] \
  [get_bd_pins xadc_wiz_0/m_axis_resetn] \
  [get_bd_pins axi_fan_control_0/s_axi_aresetn] \
  [get_bd_pins interrupt_sync_0/source_resetn]
  connect_bd_net -net spi_miso_1  [get_bd_ports spi_miso] \
  [get_bd_pins axi_quad_spi_0/io1_i]
  connect_bd_net -net tieoff_0_dout  [get_bd_pins tieoff_1/dout] \
  [get_bd_pins axi_uart16550_0/freeze]
  connect_bd_net -net xadc_wiz_0_temp_out  [get_bd_pins xadc_wiz_0/temp_out] \
  [get_bd_pins mig_7series_0/device_temp_i] \
  [get_bd_pins axi_fan_control_0/temp_in]
  connect_bd_net -net xlconstant_0_dout  [get_bd_pins tready_always_ready/dout] \
  [get_bd_pins xadc_wiz_0/m_axis_tready]

  # Create address segments
  assign_bd_address -offset 0x00000000 -range 0x00010000000000000000 -target_address_space [get_bd_addr_spaces cpu_0/m_axi_cpu] [get_bd_addr_segs northbridge/axi_riscv_atomics_wrapper_0/s_axi_in/reg0] -force
  assign_bd_address -offset 0x44000000 -range 0x00001000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs PmodGPIO_0/AXI_LITE_GPIO/Reg0] -force
  assign_bd_address -offset 0x0C000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs ariane_peripherals_0/s_axi_plic/reg0] -force
  assign_bd_address -offset 0x18000000 -range 0x00040000 -with_name SEG_ariane_peripherals_0_reg0_1 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs ariane_peripherals_0/s_axi_timer/reg0] -force
  assign_bd_address -offset 0x00010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs axi_bram_ctrl_0/S_AXI/Mem0] -force
  assign_bd_address -offset 0x41E00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs eth_0/axi_dma_0/S_AXI_LITE/Reg] -force
  assign_bd_address -offset 0x40C00000 -range 0x00040000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs eth_0/axi_ethernet_0/s_axi/Reg0] -force
  assign_bd_address -offset 0x00020000 -range 0x00010000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs axi_fan_control_0/s_axi/reg0] -force
  assign_bd_address -offset 0x40800000 -range 0x00010000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs axi_iic_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x20000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs axi_quad_spi_0/aximm/MEM0] -force
  assign_bd_address -offset 0x10000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs axi_uart16550_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x02000000 -range 0x00040000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs clint_0/s_axi_clint/reg0] -force
  assign_bd_address -offset 0x00000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs cpu_debug/s_axi_dmi_jtag/reg0] -force
  assign_bd_address -offset 0x80000000 -range 0x40000000 -target_address_space [get_bd_addr_spaces cpu_debug/m_axi_dmi_jtag] [get_bd_addr_segs mig_7series_0/memmap/memaddr] -force
  assign_bd_address -offset 0x44000000 -range 0x00001000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs PmodGPIO_0/AXI_LITE_GPIO/Reg0] -force
  assign_bd_address -offset 0x0C000000 -range 0x04000000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs ariane_peripherals_0/s_axi_plic/reg0] -force
  assign_bd_address -offset 0x18000000 -range 0x00040000 -with_name SEG_ariane_peripherals_0_reg0_1 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs ariane_peripherals_0/s_axi_timer/reg0] -force
  assign_bd_address -offset 0x00010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs axi_bram_ctrl_0/S_AXI/Mem0] -force
  assign_bd_address -offset 0x41E00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs eth_0/axi_dma_0/S_AXI_LITE/Reg] -force
  assign_bd_address -offset 0x40C00000 -range 0x00040000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs eth_0/axi_ethernet_0/s_axi/Reg0] -force
  assign_bd_address -offset 0x00020000 -range 0x00010000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs axi_fan_control_0/s_axi/reg0] -force
  assign_bd_address -offset 0x40800000 -range 0x00010000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs axi_iic_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x20000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs axi_quad_spi_0/aximm/MEM0] -force
  assign_bd_address -offset 0x10000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs axi_uart16550_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x02000000 -range 0x00040000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs clint_0/s_axi_clint/reg0] -force
  assign_bd_address -offset 0x00000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs cpu_debug/s_axi_dmi_jtag/reg0] -force
  assign_bd_address -offset 0x80000000 -range 0x40000000 -target_address_space [get_bd_addr_spaces northbridge/axi_riscv_atomics_wrapper_0/m_axi_out] [get_bd_addr_segs mig_7series_0/memmap/memaddr] -force
  assign_bd_address -offset 0x80000000 -range 0x40000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs mig_7series_0/memmap/memaddr] -force
  assign_bd_address -offset 0x80000000 -range 0x40000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs mig_7series_0/memmap/memaddr] -force

  # Exclude Address Segments
  exclude_bd_addr_seg -offset 0x44000000 -range 0x00001000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs PmodGPIO_0/AXI_LITE_GPIO/Reg0]
  exclude_bd_addr_seg -offset 0x00000000 -range 0x00010000000000000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs ariane_peripherals_0/s_axi_plic/reg0]
  exclude_bd_addr_seg -offset 0x00000000 -range 0x00010000000000000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs ariane_peripherals_0/s_axi_timer/reg0]
  exclude_bd_addr_seg -offset 0x00010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs axi_bram_ctrl_0/S_AXI/Mem0]
  exclude_bd_addr_seg -offset 0x41E00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs eth_0/axi_dma_0/S_AXI_LITE/Reg]
  exclude_bd_addr_seg -offset 0x40C00000 -range 0x00040000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs eth_0/axi_ethernet_0/s_axi/Reg0]
  exclude_bd_addr_seg -offset 0x00020000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs axi_fan_control_0/s_axi/reg0]
  exclude_bd_addr_seg -offset 0x40800000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs axi_iic_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x20000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs axi_quad_spi_0/aximm/MEM0]
  exclude_bd_addr_seg -offset 0x10000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs axi_uart16550_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x00000000 -range 0x00010000000000000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs clint_0/s_axi_clint/reg0]
  exclude_bd_addr_seg -offset 0x00000000 -range 0x00010000000000000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data] [get_bd_addr_segs cpu_debug/s_axi_dmi_jtag/reg0]
  exclude_bd_addr_seg -offset 0x44000000 -range 0x00001000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs PmodGPIO_0/AXI_LITE_GPIO/Reg0]
  exclude_bd_addr_seg -offset 0x00000000 -range 0x00010000000000000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs ariane_peripherals_0/s_axi_plic/reg0]
  exclude_bd_addr_seg -offset 0x00000000 -range 0x00010000000000000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs ariane_peripherals_0/s_axi_timer/reg0]
  exclude_bd_addr_seg -offset 0x00010000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs axi_bram_ctrl_0/S_AXI/Mem0]
  exclude_bd_addr_seg -offset 0x41E00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs eth_0/axi_dma_0/S_AXI_LITE/Reg]
  exclude_bd_addr_seg -offset 0x40C00000 -range 0x00040000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs eth_0/axi_ethernet_0/s_axi/Reg0]
  exclude_bd_addr_seg -offset 0x00020000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs axi_fan_control_0/s_axi/reg0]
  exclude_bd_addr_seg -offset 0x40800000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs axi_iic_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x20000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs axi_quad_spi_0/aximm/MEM0]
  exclude_bd_addr_seg -offset 0x10000000 -range 0x00010000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs axi_uart16550_0/S_AXI/Reg]
  exclude_bd_addr_seg -offset 0x00000000 -range 0x00010000000000000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs clint_0/s_axi_clint/reg0]
  exclude_bd_addr_seg -offset 0x00000000 -range 0x00010000000000000000 -target_address_space [get_bd_addr_spaces eth_0/axi_dma_0/Data_SG] [get_bd_addr_segs cpu_debug/s_axi_dmi_jtag/reg0]

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.947322",
   "Default View_TopLeft":"2033,-188",
   "ExpandedHierarchyInLayout":"/northbridge",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0 TLS
#  -string -flagsOSRD
preplace port ja -pg 1 -lvl 7 -x 21620 -y 1710 -defaultsOSRD
preplace port audio_codec_iic -pg 1 -lvl 7 -x 21620 -y 1520 -defaultsOSRD
preplace port sys_diff_clock -pg 1 -lvl 0 -x -80 -y 430 -defaultsOSRD
preplace port usb_uart -pg 1 -lvl 7 -x 21620 -y 1850 -defaultsOSRD
preplace port ddr3_sdram -pg 1 -lvl 7 -x 21620 -y 400 -defaultsOSRD
preplace port eth_rgmii -pg 1 -lvl 7 -x 21620 -y 1190 -defaultsOSRD
preplace port eth_mdio_mdc -pg 1 -lvl 7 -x 21620 -y 1210 -defaultsOSRD
preplace port port-id_reset -pg 1 -lvl 0 -x -80 -y 450 -defaultsOSRD
preplace port port-id_spi_clk_o -pg 1 -lvl 7 -x 21620 -y 2080 -defaultsOSRD
preplace port port-id_spi_mosi -pg 1 -lvl 7 -x 21620 -y 2040 -defaultsOSRD
preplace port port-id_spi_miso -pg 1 -lvl 0 -x -80 -y 1960 -defaultsOSRD
preplace port port-id_jtag_tdo -pg 1 -lvl 7 -x 21620 -y 760 -defaultsOSRD
preplace port port-id_jtag_tck -pg 1 -lvl 0 -x -80 -y 330 -defaultsOSRD
preplace port port-id_jtag_tms -pg 1 -lvl 0 -x -80 -y 350 -defaultsOSRD
preplace port port-id_jtag_tdi -pg 1 -lvl 0 -x -80 -y 370 -defaultsOSRD
preplace port port-id_jtag_trst_n -pg 1 -lvl 0 -x -80 -y 310 -defaultsOSRD
preplace port port-id_fan_pwm -pg 1 -lvl 7 -x 21620 -y 670 -defaultsOSRD
preplace port port-id_fan_tach -pg 1 -lvl 0 -x -80 -y 760 -defaultsOSRD
preplace portBus spi_ss -pg 1 -lvl 7 -x 21620 -y 2100 -defaultsOSRD
preplace portBus phy_reset_out -pg 1 -lvl 7 -x 21620 -y 1450 -defaultsOSRD
preplace inst axi_bram_ctrl_0 -pg 1 -lvl 5 -x 20990 -y 870 -defaultsOSRD
preplace inst tieoff_1 -pg 1 -lvl 4 -x 1840 -y 10930 -defaultsOSRD
preplace inst axi_uart16550_0 -pg 1 -lvl 5 -x 20990 -y 1860 -defaultsOSRD
preplace inst peripherals_clockgen -pg 1 -lvl 1 -x 90 -y 850 -defaultsOSRD
preplace inst axi_quad_spi_0 -pg 1 -lvl 5 -x 20990 -y 2070 -defaultsOSRD
preplace inst PmodGPIO_0 -pg 1 -lvl 5 -x 20990 -y 1710 -defaultsOSRD
preplace inst axi_iic_0 -pg 1 -lvl 5 -x 20990 -y 1540 -defaultsOSRD
preplace inst reset_polarity_conv -pg 1 -lvl 2 -x 420 -y 690 -defaultsOSRD
preplace inst bootrom_wrapper_0 -pg 1 -lvl 6 -x 21445 -y 840 -defaultsOSRD
preplace inst ariane_peripherals_0 -pg 1 -lvl 5 -x 20990 -y 1330 -defaultsOSRD
preplace inst atop_tieoff_0 -pg 1 -lvl 4 -x 1840 -y 10150 -defaultsOSRD
preplace inst irqconcat -pg 1 -lvl 4 -x 1840 -y 10450 -defaultsOSRD
preplace inst cpu_0 -pg 1 -lvl 3 -x 980 -y 750 -defaultsOSRD
preplace inst clint_0 -pg 1 -lvl 5 -x 20990 -y 1080 -defaultsOSRD
preplace inst northbridge -pg 1 -lvl 4 -x 1840 -y -34 -defaultsOSRD
preplace inst eth_0 -pg 1 -lvl 3 -x 980 -y 1250 -defaultsOSRD
preplace inst cpu_reset_gen -pg 1 -lvl 2 -x 420 -y 550 -defaultsOSRD
preplace inst mig_7series_0 -pg 1 -lvl 5 -x 20990 -y 450 -defaultsOSRD
preplace inst cpu_debug -pg 1 -lvl 3 -x 980 -y 300 -defaultsOSRD
preplace inst atop_tieoff -pg 1 -lvl 2 -x 420 -y 50 -defaultsOSRD
preplace inst memory_reset_synch -pg 1 -lvl 2 -x 420 -y 190 -defaultsOSRD
preplace inst axi_fan_control_0 -pg 1 -lvl 5 -x 20990 -y 660 -defaultsOSRD
preplace inst xadc_wiz_0 -pg 1 -lvl 4 -x 1840 -y -530 -defaultsOSRD
preplace inst tready_always_ready -pg 1 -lvl 5 -x 20990 -y 150 -defaultsOSRD
preplace inst interrupt_sync_0 -pg 1 -lvl 3 -x 980 -y 1470 -defaultsOSRD
preplace inst irq_ila -pg 1 -lvl 6 -x 21445 -y 1080 -defaultsOSRD
preplace inst northbridge|axi_interconnect_0 -pg 1 -lvl 2 -x 2520 -y 546 -defaultsOSRD
preplace inst northbridge|axi_riscv_atomics_wrapper_0 -pg 1 -lvl 1 -x 1970 -y -24 -defaultsOSRD
preplace inst northbridge|axidebug_0 -pg 1 -lvl 2 -x 2520 -y -34 -defaultsOSRD
preplace netloc ariane_peripherals_0_irq_out 1 2 4 740 860 1530 1854 20670J 970 21180
preplace netloc atop_tieoff_0_dout 1 4 1 20750 1110n
preplace netloc atop_tieoff_dout 1 2 1 700 50n
preplace netloc axi_bram_ctrl_0_bram_addr_a 1 5 1 21230 850n
preplace netloc axi_bram_ctrl_0_bram_clk_a 1 5 1 21170 820n
preplace netloc axi_bram_ctrl_0_bram_en_a 1 5 1 21190 840n
preplace netloc axi_dma_0_mm2s_introut 1 3 1 1270 1260n
preplace netloc axi_dma_0_s2mm_introut 1 3 1 1250 1280n
preplace netloc axi_fan_control_0_irq 1 2 4 700 560 1330J 1444 20600J 560 21170
preplace netloc axi_fan_control_0_pwm 1 5 2 NJ 670 NJ
preplace netloc axi_quad_spi_0_io0_o 1 5 2 NJ 2040 NJ
preplace netloc axi_quad_spi_0_ip2intc_irpt 1 3 3 1540 2514 20780J 1630 21210
preplace netloc axi_quad_spi_0_sck_o 1 5 2 NJ 2080 NJ
preplace netloc axi_quad_spi_0_ss_o 1 5 2 NJ 2100 NJ
preplace netloc axi_uart16550_0_ip2intc_irpt 1 3 3 1550 2834 20790J 1950 21170
preplace netloc bootrom_wrapper_0_rdata_o 1 5 2 21230J 920 21590
preplace netloc clint_0_ipi_o 1 2 4 720 1110 1310J 1994 20690J 1170 21210
preplace netloc clint_0_timer_irq_o 1 2 4 710 1120 1300J 2004 20700J 1180 21170
preplace netloc clk_wiz_0_clk_out1 1 1 5 220 290 670 170 1400 1054 20720 990 21190
preplace netloc cpu_0_m_axi_cpu_awatop 1 3 1 1420 256n
preplace netloc cpu_debug_debug_req_irq 1 2 4 730 870 1360 1864 20680J 980 21200J
preplace netloc cpu_debug_jtag_tdo 1 3 4 1480J 1184 2860J 300 NJ 300 21590J
preplace netloc cpu_debug_ndmreset 1 1 5 240 440 NJ 440 1430 1204 2880J 320 21220J
preplace netloc cpu_interconnect_aresetn_1 1 2 2 610J 150 1320
preplace netloc cpu_reset_gen_peripheral_aresetn 1 2 3 650 590 1540 1474 20740
preplace netloc eth_0_mac_irq 1 3 1 1230 1320n
preplace netloc eth_0_phy_reset_out1 1 3 4 1260J 2184 20760J 1450 NJ 1450 NJ
preplace netloc eth_clockgen_clk_125 1 1 2 240 920 610J
preplace netloc eth_clockgen_clk_200 1 1 2 200 930 600J
preplace netloc fan_tach_1 1 0 5 -60J 420 NJ 420 620J 470 1460J 1354 20590J
preplace netloc interrupt_synchroniz_0_irq_out 1 3 1 1220 1470n
preplace netloc irqconcat_dout 1 4 2 20770 1190 21230
preplace netloc jtag_tck_1 1 0 3 NJ 330 NJ 330 NJ
preplace netloc jtag_tdi_1 1 0 3 NJ 370 NJ 370 NJ
preplace netloc jtag_tms_1 1 0 3 NJ 350 NJ 350 NJ
preplace netloc jtag_trst_n_1 1 0 3 NJ 310 NJ 310 NJ
preplace netloc mig_7series_0_mmcm_locked 1 0 6 -30 940 NJ 940 NJ 940 1320J 1654 20620J 770 21180
preplace netloc mig_7series_0_ui_addn_clk_0 1 0 6 -20 400 NJ 400 640J 460 1490J 1214 2900J 330 21180
preplace netloc mig_7series_0_ui_clk_sync_rst 1 1 5 230 410 630J 450 1500J 1224 2910J 340 21170
preplace netloc mig_aclk_1 1 2 4 740 880 1470 1564 20610 760 21190
preplace netloc proc_sys_reset_0_peripheral_aresetn 1 2 1 690 230n
preplace netloc reset_2 1 0 5 NJ 450 NJ 450 600J 480 1450J 1364 2940J
preplace netloc reset_polarity_conv_Res 1 2 3 680 500 1520 1384 20580
preplace netloc spi_miso_1 1 0 6 NJ 1960 NJ 1960 NJ 1960 1240J 2844 20800J 1960 21170
preplace netloc tieoff_0_dout 1 4 1 20810J 1890n
preplace netloc xadc_wiz_0_temp_out 1 4 1 20740 -420n
preplace netloc xlconstant_0_dout 1 4 2 NJ -620 21170
preplace netloc ETH_DMA_AXI_0_1 1 3 1 1340 156n
preplace netloc PmodGPIO_0_Pmod_out 1 5 2 NJ 1710 NJ
preplace netloc axi_iic_0_IIC 1 5 2 NJ 1520 NJ
preplace netloc axi_interconnect_0_M01_AXI 1 4 1 20660 446n
preplace netloc axi_interconnect_0_M02_AXI 1 2 3 690 490 1440J 1374 2830
preplace netloc axi_interconnect_0_M03_AXI 1 2 3 640 510 1350J 1394 2840
preplace netloc axi_interconnect_0_M04_AXI 1 4 1 20640 646n
preplace netloc axi_interconnect_0_M05_AXI 1 4 1 20730 526n
preplace netloc axi_interconnect_0_M07_AXI 1 4 1 2870 566n
preplace netloc axi_interconnect_0_M08_AXI 1 4 1 20630 586n
preplace netloc axi_interconnect_0_M09_AXI 1 4 1 20650 606n
preplace netloc axi_interconnect_0_M10_AXI 1 4 1 2890 626n
preplace netloc axi_uart16550_0_UART 1 5 2 NJ 1850 NJ
preplace netloc cpu_0_m_axi_cpu 1 3 1 1300 -124n
preplace netloc cpu_debug_m_axi_dmi_jtag 1 3 1 1330 216n
preplace netloc eth_0_M_AXI 1 3 1 1410 176n
preplace netloc eth_0_eth_mdio_mdc 1 3 4 1280J 2084 20710J 1200 NJ 1200 21600J
preplace netloc eth_0_eth_rgmii 1 3 4 1290J 2094 20730J 1210 NJ 1210 21590J
preplace netloc mig_7series_0_DDR3 1 5 2 NJ 400 NJ
preplace netloc northbridge_M00_AXI 1 4 1 2890 410n
preplace netloc northbridge_M06_AXI 1 4 1 2850 666n
preplace netloc northbridge_M12_AXI 1 2 3 740 160 1310J 1044 2820
preplace netloc northbridge_M13_AXI 1 4 1 2920 620n
preplace netloc sys_diff_clock_1 1 0 5 NJ 430 NJ 430 NJ 430 1510J 1314 2930J
preplace netloc northbridge|S02_ARESETN_1 1 0 2 NJ 376 2300
preplace netloc northbridge|S02_ARESETN_2 1 0 2 1770 356 2360
preplace netloc northbridge|aclk1_1 1 0 2 1740 336 2320
preplace netloc northbridge|axi_riscv_atomics_wrapper_0_m_axi_out_awatop 1 0 2 1760 246 2290
preplace netloc northbridge|axi_riscv_atomics_wrapper_0_m_axi_out_awatop1 1 1 1 2300 -24n
preplace netloc northbridge|clk_wiz_0_clk_out1 1 0 2 NJ 236 2370
preplace netloc northbridge|dummy_irq_in_1 1 0 1 1750 -4n
preplace netloc northbridge|mig_7series_0_ui_clk 1 0 2 NJ 276 2350
preplace netloc northbridge|probe5_1 1 0 2 NJ 396 2330
preplace netloc northbridge|reset_polarity_conv_Res 1 0 2 NJ 296 2340
preplace netloc northbridge|CPU_AXI_1 1 0 2 1740 -124 N
preplace netloc northbridge|Conn3 1 2 1 2700 506n
preplace netloc northbridge|Conn4 1 2 1 2690 546n
preplace netloc northbridge|DEBUG_MODULE_AXI_1 1 0 2 NJ 216 N
preplace netloc northbridge|ETH_DMA_AXI_0_1 1 0 2 NJ 156 N
preplace netloc northbridge|ETH_DMA_AXI_1_1 1 0 2 NJ 176 N
preplace netloc northbridge|axi_interconnect_0_M00_AXI 1 2 1 N 426
preplace netloc northbridge|axi_interconnect_0_M01_AXI 1 2 1 N 446
preplace netloc northbridge|axi_interconnect_0_M02_AXI 1 2 1 N 466
preplace netloc northbridge|axi_interconnect_0_M03_AXI 1 2 1 N 486
preplace netloc northbridge|axi_interconnect_0_M05_AXI 1 2 1 N 526
preplace netloc northbridge|axi_interconnect_0_M07_AXI 1 2 1 N 566
preplace netloc northbridge|axi_interconnect_0_M08_AXI 1 2 1 N 586
preplace netloc northbridge|axi_interconnect_0_M09_AXI 1 2 1 N 606
preplace netloc northbridge|axi_interconnect_0_M10_AXI 1 2 1 N 626
preplace netloc northbridge|axi_interconnect_0_M11_AXI 1 2 1 2680 646n
preplace netloc northbridge|axi_interconnect_0_M12_AXI 1 2 1 2670 666n
preplace netloc northbridge|axi_riscv_atomics_wrapper_0_m_axi_out 1 1 1 2310 -104n
levelinfo -pg 1 -80 90 420 980 1840 20990 21445 21620
levelinfo -hier northbridge * 1970 2520 *
pagesize -pg 1 -db -bbox -sgen -230 -800 22870 12390
pagesize -hier northbridge -db -bbox -sgen 1710 -184 2730 996
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}


cr_bd_SoC ""

# patches
open_bd_design $origin_dir/scripts/Vivado/project/RVSoC.srcs/sources_1/bd/SoC/SoC.bd
set_property CONFIG.C_USE_STARTUP 0 [get_bd_cells /axi_quad_spi_0]
catch {
  connect_bd_net [get_bd_ports spi_clk_o] [get_bd_pins axi_quad_spi_0/sck_o]
}
save_bd_design
close_bd_design SoC

set_property REGISTERED_WITH_MANAGER "1" [get_files SoC.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files SoC.bd ] 
